title: UNLV ECON 490 Capstone Proceedings
tagline: A working paper series of undergraduate capstone research from UNLV Economics.
description: A working paper series of undergraduate capstone research from UNLV Economics.
contact_email: "farolmarkjayson@yahoo.com"
author:
  email: "farolmarkjayson@yahoo.com"

url: "https://markjayson13.github.io"
baseurl: "/UNLVECON490Journal"
permalink: /:categories/:title/
home_preview_length: 160

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "custom"

markdown: kramdown

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-remote-theme

defaults:
  - scope:
      path: "index.md"
      type: "pages"
    values:
      layout: splash
  - scope:
      path: "issues"
      type: "pages"
    values:
      layout: issue
  - scope:
      path: "issues/*/paper-*.md"
    values:
      layout: paper
  - scope:
      path: "policies"
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single

exclude:
  - templates
  - tools
  - vendor
  - Gemfile
  - Gemfile.lock
