title: UNLV ECON 490 Capstone Proceedings
description: Undergraduate economics capstone papers organized by semester and year.
url: "https://markjayson13.github.io"
baseurl: "/UNLVECON490Journal"
permalink: /:categories/:title/
contact_email: "econ490journal@unlv.edu"
home_preview_length: 160

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "custom"

markdown: kramdown

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: false
  - scope:
      path: "issues"
      type: "pages"
    values:
      classes: wide
  - scope:
      path: "policies"
      type: "pages"
    values:
      classes: wide
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: false

exclude:
  - templates
  - tools
  - vendor
  - Gemfile
  - Gemfile.lock
